### ISSUE TITLE
Certain Executions of performSwap will break with Istanbul hard fork

### ISSUE THREAD

**Issue by ritzdorf** [TotlePlatform/contracts#1]
### Background

The upcoming [Istanbul](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1679.md) Ethereum hardfork contains the [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884). EIP-1884 will, besides other things, raise the gas cost of the EVM `SLOAD` instruction from 200 to 800 gas.

### Issue Description

When the  `TotlePrimary` contract executes the `performSwap` function, it might execute the `minimumRateFailed` function, which internally calls `getDecimals` on the target token contract. As part of this call, `getDecimals` only passes 5000 gas:

https://github.com/TotlePlatform/contracts/blob/a7e15741895ecc1b5efd828d1ebd34e5a818303b/contracts/lib/Utils.sol#L49-L57

If this the target token is Augur's REP token, then the [Delegator](https://etherscan.io/address/0x1985365e9f78359a9b6ad760e32412f4a445e862#code) will be called. This call currently consumes 4511 gas and successfully returns 18.

However, this call also contains three invocations of SLOAD, so it will cost 6311 after the activation of the Istanbul hard fork. Then, the call will fail (as it is out-of-gas). `TotlePrimary` will interpret the falling call as `0` decimals:

https://github.com/TotlePlatform/contracts/blob/a7e15741895ecc1b5efd828d1ebd34e5a818303b/contracts/lib/Utils.sol#L59-L66

As the decimals are used to calculate token quantities, **incorrect token quantities will be computed**. **Hence, users would be as the security check for the minimum rate could be circumvented**.

### Example

The scenario described above recently took place in the following [transaction](https://etherscan.io/tx/0xfe31c6c118fe6a6d4dc625991f7978ade1f0ec84665784b23f998872997ab474). 
This trade converted 0.06978 Ether into 1.497 Reputation (REP) tokens. 

### Additional Information

[ChainSecurity](https://chainsecurity.com/) has conducted some analysis on the effects of EIP-1884. The intermediate results can be found [here](https://gist.github.com/ritzdorf/1c6bd72955391e831f8a397d3152b4e0).

Martin Holst Swende has collected information on the effects of EIP-1884 [here](https://github.com/holiman/eip-1884-security).

### Contact

Feel free to contact hubert@chainsecurity.com or `@HRitzdorf` on Telegram in case of questions or comments.

**Comment by nateawelch** [comment]
Hey! Very much appreciate this. Glad there is a group doing this sort of proactive outreach. We will have this updated in the next few days.

For my own curiosity, how did your team go about searching for these potential bugs? My first guess is searching all debug traces for CALLS with a gas stipend that isn't all gas available to its caller.

**Comment by nateawelch** [comment]
This has been fixed in the latest release

**Comment by ritzdorf** [comment]
> For my own curiosity, how did your team go about searching for these potential bugs? My first guess is searching all debug traces for CALLS with a gas stipend that isn't all gas available to its caller.

Sorry. I never managed to answer this. Yes, we searched all debug traces for CALLs with a fixed amount of gas (gas stipend is the most common version) and computed whether that amount would still be sufficient in the future.
